name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - testing_net
    volumes:
      - ./server/config.ini:/config.ini
  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - NOMBRE=Ana
      - APELLIDO=Fernandez
      - DOCUMENTO=49735218
      - NACIMIENTO=1989-03-16
      - NUMERO=3961
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml
      - ./.data/agency-1.csv:/agency.csv
  client2:
    container_name: client2
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=2
      - NOMBRE=Ana
      - APELLIDO=Gomez
      - DOCUMENTO=49546596
      - NACIMIENTO=2003-06-06
      - NUMERO=7464
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml
      - ./.data/agency-2.csv:/agency.csv
  client3:
    container_name: client3
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=3
      - NOMBRE=Ana
      - APELLIDO=Gomez
      - DOCUMENTO=40972948
      - NACIMIENTO=1989-03-02
      - NUMERO=6522
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml
      - ./.data/agency-3.csv:/agency.csv
  client4:
    container_name: client4
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=4
      - NOMBRE=Maria
      - APELLIDO=Fernandez
      - DOCUMENTO=22620985
      - NACIMIENTO=1952-06-22
      - NUMERO=871
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml
      - ./.data/agency-4.csv:/agency.csv
  client5:
    container_name: client5
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=5
      - NOMBRE=Maria
      - APELLIDO=Lorca
      - DOCUMENTO=28724809
      - NACIMIENTO=1950-06-22
      - NUMERO=693
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml
      - ./.data/agency-5.csv:/agency.csv

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
