name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - testing_net
    volumes:
      - ./server/config.ini:/config.ini
  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - NOMBRE=Carlos
      - APELLIDO=Diaz
      - DOCUMENTO=35849867
      - NACIMIENTO=1990-01-18
      - NUMERO=8579
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml
      - ./.data/agency-1.csv:/agency.csv
  client2:
    container_name: client2
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=2
      - NOMBRE=Lionel
      - APELLIDO=Fernandez
      - DOCUMENTO=37556198
      - NACIMIENTO=1968-02-15
      - NUMERO=6713
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml
      - ./.data/agency-2.csv:/agency.csv
  client3:
    container_name: client3
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=3
      - NOMBRE=Maria
      - APELLIDO=Diaz
      - DOCUMENTO=45755729
      - NACIMIENTO=1970-02-06
      - NUMERO=4960
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml
      - ./.data/agency-3.csv:/agency.csv
  client4:
    container_name: client4
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=4
      - NOMBRE=Lionel
      - APELLIDO=Lorca
      - DOCUMENTO=37449668
      - NACIMIENTO=1950-10-18
      - NUMERO=9613
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml
      - ./.data/agency-4.csv:/agency.csv
  client5:
    container_name: client5
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=5
      - NOMBRE=Ana
      - APELLIDO=Fernandez
      - DOCUMENTO=45482563
      - NACIMIENTO=1963-07-06
      - NUMERO=2751
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml
      - ./.data/agency-5.csv:/agency.csv

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
