name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - TOTAL_AGENCIES=3
    networks:
      - testing_net
    volumes:
      - ./server/config.ini:/config.ini
  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - NOMBRE=Lionel
      - APELLIDO=Fernandez
      - DOCUMENTO=23945560
      - NACIMIENTO=1992-03-18
      - NUMERO=1953
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml
      - ./.data/agency-1.csv:/agency.csv
  client2:
    container_name: client2
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=2
      - NOMBRE=Ana
      - APELLIDO=Diaz
      - DOCUMENTO=26285830
      - NACIMIENTO=1953-05-10
      - NUMERO=3219
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml
      - ./.data/agency-2.csv:/agency.csv
  client3:
    container_name: client3
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=3
      - NOMBRE=Santiago
      - APELLIDO=Fernandez
      - DOCUMENTO=32813332
      - NACIMIENTO=2001-11-09
      - NUMERO=3152
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml
      - ./.data/agency-3.csv:/agency.csv

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
